<main class="backend">

    <header class="backendLeft">
        <nav class="backendLeftNav flexColumn">
            <a class="flexColumn" href="<?=$requestUrl ?>/backend"><i class="fas fa-home"></i>Home</a>
            <a class="flexColumn" href="<?=$requestUrl ?>/backend/posts">
                <i class="far fa-newspaper"></i>
                Posts
                <div class="submenu">
                    <a class="flexColumn" href="<?=$requestUrl ?>/backend/posts">all posts</a>
                    <a class="flexColumn" href="<?=$requestUrl ?>/backend/posts/createpost">create post</a>                
                </div>
            </a>
            <a class="flexColumn" href="<?=$requestUrl ?>/backend/users">
            <i class="fas fa-users"></i>
            Users
            
            </a>
        </nav>
    </header>


    <div class="flex spaceBetween backendMiddle">
        <h2>waiting comments</h2>
            <div class="writtenCommentsAll">

                <?php if(isset($allCommentsStatusWaiting)): ?>
                <?php foreach($allCommentsStatusWaiting as $comment): ?>
                

                <div class="writtenCommentOne">
                    <div class="writtenCommentOneBody">
                        <p><?= $comment['body']; ?></p>
                    </div>
                    <div class="writtenCommentOneUsername">                            
                        <i class="fas fa-calendar-alt">
                            <span class="recentPostsDate">
                                <b><?= $comment['creation_date']; ?></b> 
                            </span>
                        </i>
                        <i class="fas fa-user">
                            <?= $comment['author']; ?>
                        </i> 
                        <div><?= $comment['status']; ?></div>
                    </div>
                    <div>
                        <form action="" method="post">
                            <input type="hidden" name="comment_id" value="<?= $comment['id']; ?>">
                            <button name="send" value="acceptComment">Accept comment</button>
                        </form>
                        
                        <button>Don't accept</button>
                    </div>                        
                </div>

                <?php endforeach; ?>
                <?php endif; ?>

                
            </div>        
    </div>


    <aside class="backendRight">
        <form action="" method="POST">
            <button class="flexColumn backendBtn" type="submit" name="logout" value="logout"><i class="fas fa-sign-out-alt"></i> Logout</button>
        </form>
        <form action="" method="post">
            <button class="flexColumn backendBtn edit" type="submit" name="editAccount" value="<?= $session->getUserId();?>"><i class="fas fa-edit"></i> edit my account</button>
        </form>
        <form action="" method="post">
            <button class="flexColumn backendBtn delete" type="submit" name="deleteAccount" value="<?= $session->getUserId();?>"> <i class="fas fa-trash-alt"></i> delete account</button>
        </form>
    </aside>
    
</main>