<main class="container accueil">
    <div class="accueilTop">
        <img src="<?= $wwwUrl ?>/images/echec003.jpeg" alt="">
    </div>
    <div class="accueilBottom">
        <div class="accueilBottomLeft">
            <article class="clubInfo">
                <h2>Club Information</h2>
                <div class="clubInformation spaceBetween">
                    <div class="clubInformationImg">
                        <img src="<?= $wwwUrl ?>/images/echec004.jpeg" alt="">
                    </div>
                    
                    <div class="clubInformationDescription">
                        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Excepturi nesciunt, voluptates aliquid porro doloremque dicta neque rem veritatis pariatur saepe voluptas! </p>
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sint, quaerat corporis. Expedita doloremque labore placeat deserunt non pariatur accusantium quaerat ducimus eligendi et beatae repellat, natus officia porro voluptas iste. Lorem, ipsum dolor sit amet consectetur adipisicing elit.</p>
                        <a href="" class="recentPostsReadMore">
                            <b> Read More </b>
                        </a>
                    </div>
                </div>
                
            </article>
            <article class="clubOfficers">
                <h2>Club Officers</h2>
                <div class="clubOfficersAll flexWrap">
                    <div class="clubOfficersOne">
                        <img src="<?= $wwwUrl ?>/images/echec004.jpeg" alt="">
                        <div class="clubOfficersDescription">
                            <p><b>Charly Launay</b></p>
                            <p>Président</p>
                            <p>charly.launay@gmail.com</p>
                            <p>Tél. 06.22.04.69.10</p>
                        </div>
                    </div>

                    <div class="clubOfficersOne">
                        <img src="<?= $wwwUrl ?>/images/echec003.jpeg" alt="">
                        <div class="clubOfficersDescription">
                            <p><b>Foued Eddif</b></p>
                            <p>Trésorier</p>
                            <p>correspondant.cema@gmail.com</p>
                            <p>Tél. 06.22.04.69.10</p>
                        </div>
                    </div>

                    <div class="clubOfficersOne">
                            <img src="<?= $wwwUrl ?>/images/echec004.jpeg" alt="">
                            <div class="clubOfficersDescription">
                                <p><b>Charly Launay</b></p>
                                <p>Président</p>
                                <p>charly.launay@gmail.com</p>
                                <p>Tél. 06.22.04.69.10</p>
                            </div>
                    </div>

                    <div class="clubOfficersOne">
                        <img src="<?= $wwwUrl ?>/images/echec003.jpeg" alt="">
                        <div class="clubOfficersDescription">
                            <p><b>Foued Eddif</b></p>
                            <p>Trésorier</p>
                            <p>correspondant.cema@gmail.com</p>
                            <p>Tél. 06.22.04.69.10</p>
                        </div>
                    </div>
                </div>
            </article>
        </div>
        <div class="accueilBottomRight">
            <section class="ourHistory">
                <h2>Our History</h2>
                <div class="OurHistoryOne">
                    <div class="ourHistoryOneDate">
                        2005
                    </div>
                    <div class="ourHistoryOneDescription">
                        <h3>Lorem Ipsum</h3>
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores ut incidunt assumenda nihil a accusantium molestiae optio debitis maxime, eaque magni id? Cum neque modi, quasi unde iste sed vitae.</p>
                    </div>
                </div>
            </section>
            <section class="usefulLinks">
                <h2>Useful Links</h2>
                <ol>
                    <li>Link one</li>
                    <li>Link two</li>
                    <li>Link tree</li>
                </ol>
            </section>
        </div>
    </div>
</main>