<main class="container contact">
    <div class="contactTop"></div>
    <div class="contactBottom">
        <div class="contactLeft">
            <h2>Contact info</h2>
            <h3>Le club d’échecs se situe sur les bords de Marne, dans le square de l’artificier Henri François,pavillon de la ludothèque, annexe de la Maison Pour Tous d’Alfort, 1, rue du Maréchal Juin, 94700 Maisons-Alfort. Station École Vétérinaire de Maisons-Alfort</h3>
            <p>Pour venir du métro: Sortir du métro en direction du Siège de la banque Bpifrance, de l’école Paul Bert et du magasin Picard. Prendre la première rue à gauche ou la rue Paul Bert entre l’école et le magasin Picard. Tourner à droite au bout de la rue, et le square se trouve sur la gauche à 200m 1 rue du Maréchal juin en face de la rue Ulysse Benne.</p>
            <div class="contactInfoBox">
                <div class="contactInfoBoxAdrese"><b>
                    Cavalier de l'Esperence <br>
                    1 rue du Maréchal Juin <br>
                    94700 Maisons-Alfort</b>
                </div>
                <div>
                        Tél: 06.22.04.69.10
                </div>
                <div>
                        e-mail: charly.launay@gmail.com
                </div>                   
            </div>                        
        </div>
        <div class="contactRight">
            <h2>Contact form</h2>
            <form action="" method="POST">
                <div class="contactFormTop">
                    <input type="text" name="name" placeholder="Name:">
                    <input type="email" name="email" placeholder="E-mail:">
                    <input type="text" name="phone" placeholder="Phone:">
                </div>
                <div>
                    <textarea name="message" id="" cols="30" rows="10" placeholder="Message:"></textarea>
                </div> 
                <div>
                    <input type="submit" class="SubmitComment" value="Send Message">
                </div>                  
                
                
            </form>
        </div>
    </div>

</main>