<main class="container lesson">
    <div class="lessonTop"></div>
    <div class="lessonBottom">
        <aside class="lessonBottomLeft">
            <section class="coursDEchecs">
                <h2>Cours d'echecs</h2>
                <div class="coursDEOne">
                    <div class="coursDEOneDate">
                        mercredi
                    </div>
                    <div class="coursDEOneDescription">                        
                        <h3>Cours ouvert à tous</h3>
                        <p>13h15 à 14h30</p>
                    </div>
                </div>
                <div class="coursDEOne">
                    <div class="coursDEOneDate">
                        vendredi
                    </div>
                    <div class="coursDEOneDescription">                        
                        <h3>Parties libres ou tournoi interne</h3>
                    </div>
                </div>
                <div class="coursDEOne">
                    <div class="coursDEOneDate">
                        samedi
                    </div>
                    <div class="coursDEOneDescription">
                        <h3>Debutants</h3>
                        <p>10h00 à 11h15</p>
                        <h3>Inities</h3>
                        <p>11h15 à 12h30</p>
                        <h3>Confirmes</h3>
                        <p>13h30 à 14h45</p>
                        <h3>Parties libres</h3>
                        <p>10h00 à 18h00</p>                       
                    </div>
                </div>
            </section>
            <section class="initiation">
                <h3>Initiation et cours d'echecs Enfants (à partir de 5 ans)</h3>
                <p>Les initiations et cours d’échecs sont transmis par des animateurs diplômés de la Fédération Française des Echecs. Pour les licenciés A en compétition notre DAFFE 2, nos forts joueurs, arbitres, problémistes... interviennent afin d’entrainer nos jeunes pour les interclubs et les tournois individuels et par équipe.</p>
            </section>
            
        </aside>
        <div class="lessonBottomRight">
            <section class="formInscr">
                <h2>Inscription form</h2>
                <form action="" method="POST">
                    <div class="formInscription">
                        <input type="text" name="name" placeholder="Nom:*">
                    </div>
                    <div class="formInscription">
                        <input type="text" name="name" placeholder="Prenom:*">
                    </div>
                    <div class="formInscription">
                        <input type="email" name="email" placeholder="E-mail:*">
                    </div>
                    <div class="formInscription">
                        <input type="date" name="birthdate" placeholder="Date de Naissance:*">
                    </div>
                    <div class="formInscription">
                        <input type="text" name="phone" placeholder="Telephone:">
                    </div>
                    <div class="formInscription">
                        <input type="text" name="city" placeholder="Ville:*">
                    </div>
                    <div class="formInscription">
                        <input type="text" name="code_postal" placeholder="code postal:*">
                    </div>
                    
                    <div class="form-check">
                        <label for="nom">L'adhesion au club est de 32 euros</label><br>
                        <small id="emailHelp" class="form-text text-muted">Sélectionnez votre choix avec cours ou sans</small> <br>
                        <input type="checkbox" class="form-check-input" name="avec">Avec cours collectif + 100 €<br>
                        <input type="checkbox" class="form-check-input" name="sans">Sans cours <br>
                        <input type="checkbox" class="form-check-input" name="membre">2nd membre de la famille avec cours - 32 €
                    </div>
                    <div class="form-check" >
                        <label class="form-check-label" for="">Une licence B (loisirs ) ou licence A (compétition) est obligatoire</label> <br>
                        <input type="radio" class="form-check-input" name="licence" value="licenceB3" checked> Licence B (- 20 ans) 3€<br>
                        <input type="radio" class="form-check-input" name="licence" value="licenceB9"> Licence B (+ 20 ans) 9€<br>
                        <input type="radio" class="form-check-input" name="licence" value="licenceA17"> Licence A (- 20 ans) 17 €<br>
                        <input type="radio" class="form-check-input" name="licence" value="licenceA49"> Licence A (+ 20ans) 49 €
                    </div>
                    <div class="form-check">
                        <label for="cotisation">Montant de la cotisation 32€ + licence + options</label>
                        <br>
                        <input class="formIn" type="text" name="cotisation" placeholder="Montant de la cotisation 32€ + licence + options">
                    </div>
                    <div class="form-check">
                        <label class="form-check-label" for="">Seriez-vous intéressé(e) par des cours FIDE +2100 Élo</label> <br>
                        <input type="radio" class="form-check-input" name="coursFIDE" value="collectif" checked> Cours collectif<br>
                        <input type="radio" class="form-check-input" name="coursFIDE" value="individuel"> Cours individuel <br>
                        <input type="radio" class="form-check-input" name="coursFIDE" value="non"> Pas intéressé
                    </div>
                    <div class="form-check">
                        <label class="form-check-label" for="">Seriez-vous intéressé(e) par des stages collectifs pendant les vacances scolaires</label> <br>
                        <input type="radio" class="form-check-input" name="stages" value="oui" checked> Oui<br>
                        <input type="radio" class="form-check-input" name="stages" value="non"> Non
                    </div>
                    <div class="formInscription">
                        <input type="submit" class="SubmitComment" value="Inscription">
                    </div>                                 
                </form>
            </section>
            
        </div>
    </div>
</main>