<main class="container blog onePost">
    <section class="blogLeft">

        <?php if(isset($oneArticle)): ?>

        <article class="postsList oneArticle">
            <h1><?= $oneArticle['title']; ?></h1>
            <img src="<?= $wwwUrl ?>/uploads/articleMainPhoto/<?= $oneArticle['article_main_photo']; ?>" alt="">
            <p><?= $oneArticle['body']; ?></p>
            <div class="postsListInfo">
                    <i class="fas fa-calendar-alt">
                        <span class="recentPostsDate">
                            <b><?= $oneArticle['creation_date']; ?></b> 
                        </span>
                    </i>
                    <i class="fas fa-user">
                        <?= $oneArticle['author']; ?>
                    </i> <br>
                    <i class="fas fa-comments">
                        no comments
                    </i>
                    <i class="fas fa-thumbs-up"> 
                        <?= $oneArticle['likes']; ?>
                    </i>
                    <i class="fas fa-thumbs-down"> 
                        <?= $oneArticle['nolikes']; ?>
                    </i>
            </div>
        </article>

         <?php endif; ?>

        <article class="postPhotoGalery">
            <h3>Photo Galery</h3>
            <div class="postPhotoGaleryAll">
                <img class="postPhotoGaleryOne" src="<?= $wwwUrl ?>/images/logo.png" alt="">
                <img class="postPhotoGaleryOne" src="<?= $wwwUrl ?>/images/echec004.jpeg" alt="">
                <img class="postPhotoGaleryOne" src="<?= $wwwUrl ?>/images/echec002.jpeg" alt="">
                <img class="postPhotoGaleryOne" src="<?= $wwwUrl ?>/images/Logo.jpg" alt="">
                <img class="postPhotoGaleryOne" src="<?= $wwwUrl ?>/images/cinematheque.jpg" alt="">
                
            </div>                   
        </article>

        <article class="postVideoGalery">
            <h3>Video Galery</h3>
            <div class="postVideoGaleryAll">
                <video class="postVideoGaleryOne" controls src="<?= $wwwUrl ?>/video/video.webm">
                    Votre navigateur ne peut pas lire cette vidéo
                </video> 
                <video class="postVideoGaleryOne" controls src="<?= $wwwUrl ?>/video/video.webm">
                    Votre navigateur ne peut pas lire cette vidéo
                </video> 
                <video class="postVideoGaleryOne" controls src="<?= $wwwUrl ?>/video/video.webm">
                    Votre navigateur ne peut pas lire cette vidéo
                </video>                   
            </div>                   
        </article>

        <article class="writtenBy">
            <h3>Written by <span class="brownLight">John Smith</span></h3>
            <div class="writtenByTop">
                <div class="writtenByTopLeft">
                    <img src="<?= $wwwUrl ?>/images/logo.png" alt="">
                </div>
                <div class="writtenByTopRight">
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Id cupiditate sit cumque obcaecati? Ipsa maxime nam eius, expedita repellat quaerat modi tenetur doloribus quisquam magni odio cumque. Error, aut vero?</p>
                </div>
            </div>                   
        </article>



        <article class="writtenComments">
            <h2>Comments</h2>
            <div class="writtenCommentsAll">

                <?php if(isset($commentsForOneArticle)): ?>
                <?php foreach($commentsForOneArticle as $comment): ?>
                

                <div class="writtenCommentOne">
                    <div class="writtenCommentOneBody">
                        <p><?= $comment['body']; ?></p>
                    </div>
                    <div class="writtenCommentOneUsername">                            
                        <i class="fas fa-calendar-alt">
                            <span class="recentPostsDate">
                                <b><?= $comment['creation_date']; ?></b> 
                            </span>
                        </i>
                        <i class="fas fa-user">
                            <?= $comment['author']; ?>
                        </i> <br>
                    </div>                        
                </div>

                <?php endforeach; ?>
                <?php else: ?>

                <div class="writtenCommentOne"> 
                   <p>no comments yet !!!</p>  
                </div>

                <?php endif; ?>

                
            </div>                   
        </article>

        <div class="formLeaveComment">
            <h2>Leave a comment</h2>
            <form action="" method="POST">
                <?php if(isset($oneArticle)): ?>
                    <input type="hidden" name="article_id" value="<?= $oneArticle['id']; ?>">
                <?php endif; ?>
                <?php if(isset($session)): ?>
                    <input type="hidden" name="user_id" value="<?= $session->getUserId(); ?>">
                <?php endif;?>
               
                <div>
                    <textarea name="body" cols="30" rows="10" placeholder="Your comment*"></textarea>
                </div>
                
                <div>
                    
                    <input type="submit" class="SubmitComment" value="Submit Comment">
                </div>
            </form>
        </div>

       

    </section>

    <aside class="blogRight">
        <div class="recentPostsList">
            <h2>Recent Posts</h2>

            <?php if(isset($articles)): ?>
            <?php foreach($articles as $article): ?>

            <div class="recentPosts flex spaceBetween">
                <div class="recentPostsLeft">
                    <img src="<?= $wwwUrl ?>/uploads/articleMainPhoto/<?= $article['article_main_photo']; ?>" alt="">
                </div>
                <div class="recentPostsRight">
                    <div class="recentPostsDate">
                        <b><?= $article['creation_date']; ?></b> 
                    </div>
                    <div class="recentPostsTitle">
                        <h3><?= $article['title']; ?></h3> 
                    </div>
                    <a href="<?=$requestUrl ?>/blog/post?post_id=<?= $article['id']; ?>" class="recentPostsReadMore">
                        <b> Read More </b>
                    </a>
                </div>
            </div>

            <?php endforeach; ?>
            <?php endif; ?>

        </div>

        <div class="recentCommentsList">
            <h2>Recent Comments</h2>

            <?php if(isset($lastFiveComments)): ?>
            <?php foreach($lastFiveComments as $last): ?>

            <div class="recentComments">
                <div class="recentCommentsTop">
                    <div class="recentCommentsLeft">
                        <img src="<?= $wwwUrl ?>/images/logo.png" alt="">
                    </div>
                    <div class="recentCommentsRight">
                        <div class="recentCommentsUsername">
                             <?= $last['author']; ?>
                        </div>
                        <div class="recentCommentsDate">
                            <b><?= $last['creation_date']; ?></b> 
                        </div>
                    </div>
                </div>
                <div class="recentCommentsBottom">
                    <a href="" class="recentCommentsBodyShort">
                        <?= $last['body']; ?>
                    </a>
                </div>
            </div>
        </div>

        <?php endforeach; ?>
        <?php endif; ?>

    </aside>

</main>