<main class="backend backendPosts">

    <header class="backendLeft">
        <nav class="backendLeftNav flexColumn">
            <a class="flexColumn" href="<?=$requestUrl ?>/backend"><i class="fas fa-home"></i>Home</a>
            <a class="flexColumn" href="<?=$requestUrl ?>/backend/posts"><i class="far fa-newspaper"></i>Posts
                <div class="submenu">
                    <a class="flexColumn" href="<?=$requestUrl ?>/backend/posts">all posts</a>
                    <a class="flexColumn" href="<?=$requestUrl ?>/backend/posts/createpost">create post</a>                
                </div>
            </a>
            <a class="flexColumn" href="<?=$requestUrl ?>/backend/users"><i class="fas fa-users"></i>Users</a>
        </nav>
    </header>


    <div class=" backendMiddle onePost">
            <h2>10 latest Posts</h2>
            <?php if(isset($articles)): ?>
            <?php foreach($articles as $article): ?>
            <div class="flex spaceBetween backendMiddleOneArticle">
                <div class="backendMiddlePhoto">
                    <img src="<?= $wwwUrl ?>/uploads/articleMainPhoto/<?= $article['article_main_photo']; ?>" alt="">
                </div>
                <div class="backendMiddleDescription">
                    <h2><?= $article['title']; ?></h2>

                    <?php   $string = strip_tags($article['body']);
                            if (strlen($string) > 100) {

                                // truncate string
                                $stringCut = substr($string, 0, 100);
                                $endPoint = strrpos($stringCut, ' ');

                                //if the string doesn't contain any space then it will cut without word basis.
                                $string = $endPoint? substr($stringCut, 0, $endPoint):substr($stringCut, 0);
                            
                            }  ?>
                    <p><?= $string; ?>...</p>
                </div>
            </div>
            <div class="backendMiddleButtons flex spaceAround">
                <a class="grey" href="<?=$requestUrl ?>/backend/posts/onepost?article_id=<?= $article['id']; ?>">
                    Read More
                    <?= $article['id']; ?>
                </a>
                <a class="green edit" href="<?=$requestUrl ?>/backend/posts/onepost/postedit?article_id=<?= $article['id']; ?>">Edit Article</a>
                <a class="red delete" href="<?=$requestUrl ?>/backend">Delete Article</a>
            </div>
            <?php endforeach; ?>
            <?php endif; ?>                   
    </div>


    <aside class="backendRight">
        <form action="" method="POST">
            <button class="flexColumn backendBtn" type="submit" name="logout" value="logout"><i class="fas fa-sign-out-alt"></i> Logout</button>
        </form>
        <form action="" method="post">
            <button class="flexColumn backendBtn edit" type="submit" name="editAccount" value="<?= $session->getUserId();?>"><i class="fas fa-edit"></i> edit my account</button>
        </form>
        <form action="" method="post">
            <button class="flexColumn backendBtn delete" type="submit" name="deleteAccount" value="<?= $session->getUserId();?>"> <i class="fas fa-trash-alt"></i> delete account</button>
        </form>
    </aside>
    
</main>