<main class="backend posts">

    <header class="backendLeft">
        <nav class="backendLeftNav flexColumn">
            <a class="flexColumn" href="<?=$requestUrl ?>/backend"><i class="fas fa-home"></i>Home</a>
            <a class="flexColumn" href="<?=$requestUrl ?>/backend/posts"><i class="far fa-newspaper"></i>Posts</a>
            <a class="flexColumn" href="<?=$requestUrl ?>/backend/users"><i class="fas fa-users"></i>Users</a>
        </nav>
    </header>


    <div class="flex spaceBetween backendMiddle">
        <div class="backendMiddleLeft">
            <h2>10 latest Posts</h2>
        </div>
        <div class="backendMiddleRight formLeaveComment">
            <h2>Create Post</h2>
            <form action="" method="POST" enctype="multipart/form-data">
                <div>
                    <input type="text" name="title" placeholder="Title">
                </div>
                <div>
                    <textarea name="body" id="" cols="30" rows="10" placeholder="body"></textarea>
                </div>
                <div>
                    <input type="text" name="author" placeholder="author">
                </div>
                <div>
                    <input type="file" name="fileToUpload" id="fileToUpload">
                </div>
                <div>
                    <input type="submit" class="SubmitComment" value="Submit Post">
                </div>
            </form>
                    
    </div>


    <aside class="backendRight">
        <form action="" method="POST">
            <button class="flexColumn backendBtn" type="submit" name="logout" value="logout"><i class="fas fa-sign-out-alt"></i> Logout</button>
        </form>
        <form action="" method="post">
            <button class="flexColumn backendBtn edit" type="submit" name="editAccount" value="<?= $session->getUserId();?>"><i class="fas fa-edit"></i> edit my account</button>
        </form>
        <form action="" method="post">
            <button class="flexColumn backendBtn delete" type="submit" name="deleteAccount" value="<?= $session->getUserId();?>"> <i class="fas fa-trash-alt"></i> delete account</button>
        </form>
    </aside>
    
</main>